daftarNama = ['Hilda','Maulana','Ckasinta','Nadya','Feggy','Peter',
              'Armelia','Arya','ahmad','Renaya','Lucky','Gracia','Yolanda',
              'Hazana','Aulia','Rida','Denis','sinta','Putri','Widi',
              'Puji','Ridwansyah','Ichsan','Meisa','Dita','Rosyanda',
              'Rizky','ita','Rendi','Annisa','ristami','Khansa','Mita','Suci',
              'Mariam','risma','Kurnia','Dwi','Diny','ayudhia','Jayanti',
              'Ferdinand','agung','saputra','Anjani','Gina','ayudhia','wendyna',
              'Wahyu','Salma','indah','Dicky','Deri','arief','ari','Indri',
              'dinda','Syahdan','Ana','Ghita','Dhea','Evi',
              'afgani','moch','Kirana','Lassandra','arif','santoso','Saepuloh',
              'Rizal','Nur','Selisa','raka','Selisa','hanna','suci',
              'Nurfa','Israqi','Israqi','zella','Brama','Dani',
              'Bayu','windi','Citra','Dinda','Yulia','Riska','irfan',
              'Regina','nita','sukmala','Pina','andriyani','Muhamad',
              'Deri','Yogi','Siti','Lulu','Sonia','Hanasira','Kania','Anisa',
              'Adi','Ira','Bagus','Ajeng','Ranti','Agus',
              'Hilmy','winda','Iman','Adnan','Muni','Rizky','Ahmad','Putri',
              'lestari','lestari','Ninne','Sri','Raka','Neneng','Ridwan',
              'Revina','robbi','Esya','Tatie','Isnaeni','Nur','hasannah',
              'rani','Rivani','juanita','Rachmawati','yolanda','Zaenal','yogie',
              'anggi','Erwin','Susanti','lusiana','saraswati','Suherdi',
              'Daniel','furqon','Muhammad','furqon','Novianti','alamda',
              'Agnes','andrian','Avrialy','andrian','Ristya','delsa',
              'Bella'
]

daftarLokasi = [
    "Andir",
    "Antapani",
    "Arcamanik",
    "Astana Anyar",
    "Babakan Ciparay",
    "Bandung Kidul",
    "Bandung Kulon",
    "Bandung Wetan",
    "Batununggal",
    "Bojongloa Kaler",
    "Bojongloa Kidul",
    "Buahbatu",
    "Cibeunying Kaler",
    "Cibeunying Kidul",
    "Cibiru",
    "Cicendo",
    "Cidadap",
    "Cinambo",
    "Coblong",
    "Gedebage",
    "Kiaracondong",
    "Lengkong",
    "Mandalajati",
    "Panyileukan",
    "Rancasari",
    "Regol",
    "Sukajadi",
    "Sukasari",
    "Sumur Bandung",
    "Ujungberung"
]

daftarHP = [
    "Samsung",
    "Xiaomi",
    "OPPO",
    "vivo",
    "realme",
    "Infinix",
    "TECNO",
    "itel",
    "Apple",
    "ASUS",
    "Huawei",
    "Honor",
    "Nokia",
    "Sony",
    "Lenovo",
    "Motorola",
    "Google Pixel",
    "ZTE",
    "Sharp",
    "Advan"
]

daftarEmail = ["@gmail.com", "@yahoo.com", "@outlook.com", "@hotmail.com"]

digitalInterest = [
    "Gaming",
    "E-commerce",
    "Fashion",
    "Beauty",
    "Technology",
    "Automotive",
    "Travel",
    "Food & Beverage",
    "Finance",
    "Cryptocurrency",
    "Sports",
    "Music",
    "Movies & Streaming",
    "Education",
    "Health & Fitness",
    "Parenting",
    "Home Living",
    "Career Development",
    "News",
    "Social Media"
]